### PR TITLE
0xDEADBEEF

### PR DESCRIPTION
**Pull request by MattTheTekie**
Some grammar correction from a native English speaker.

### CODE REVIEW

**Comment by MattTheTekie** [comment]
I was looking forward to helping out with some grammer correction.

**Comment by mistertest** [comment]
Hello @MattTheTekie. Thank you for your help and sorry, for this tardive answer. You are welcome and I have more times now, for my projects, I will see your contribution and your langage correction. As you says, I'm not a native English Speaker, I'm french with some basics. So I'll take the time to look at it and thank you again for your precious help.

**Comment by MattTheTekie** [comment]
Thank you. I'm working right now, but i got some more corrections to work on.

**Comment by MattTheTekie** [comment]
I'll work on adding more corrections in a few hours. I'm currently working on something at the moment.

**Comment by MattTheTekie** [comment]
Moved over to https://github.com/mistertest/cloud-choice/pull/3

**Pull request closed without merging**
