### PR TITLE
Much needed text corrections

### PR DESCRIPTION
**Pull request by MattTheTekie**
I did a bunch of text corrections for you. @mistertest

### CODE REVIEW

**Comment by MattTheTekie** [comment]
@mistertest How's this?

**Comment by MattTheTekie** [comment]
@mistertest How's this?

**Comment by MattTheTekie** [comment]
@mistertest

**Comment by MattTheTekie** [comment]
@mistertest are you going to accept the pr?

**Comment by mistertest** [comment]
Thank you very much @MattTheTekie  it's so helpful

**Comment by MattTheTekie** [comment]
You're welcome. I keep forgetting to mention you.

**Pull request merged**
